"""empty message

Revision ID: 65210c4fa138
Revises: 0d4aaf4429c7
Create Date: 2020-05-26 14:34:07.017000

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '65210c4fa138'
down_revision = '0d4aaf4429c7'
branch_labels = None
depends_on = None


def upgrade():
# ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('ix_comments_timestamp'), 'comments', ['timestamp'], unique=False)
    op.drop_constraint(None, 'comments', type_='foreignkey')
    op.create_foreign_key(None, 'comments', 'user', ['author_id'], ['id'])
    op.drop_column('comments', 'author')
    op.add_column('post', sa.Column('body_html', sa.String(length=140), nullable=True))
    op.create_unique_constraint(None, 'role', ['name'])
    op.create_foreign_key(None, 'role_users', 'role', ['role_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
# ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'role_users', type_='foreignkey')
    op.drop_constraint(None, 'role', type_='unique')
    op.drop_column('post', 'body_html')
    op.add_column('comments', sa.Column('author', sa.TEXT(), nullable=True))
    op.drop_constraint(None, 'comments', type_='foreignkey')
    op.create_foreign_key(None, 'comments', 'user', ['disabled'], ['id'])
    op.drop_index(op.f('ix_comments_timestamp'), table_name='comments')
    # ### end Alembic commands ###
