"""empty message

Revision ID: cae6469e368d
Revises: 65210c4fa138
Create Date: 2020-05-30 11:06:31.372000

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'cae6469e368d'
down_revision = '65210c4fa138'
branch_labels = None
depends_on = None


def upgrade():
# ### commands auto generated by Alembic - please adjust! ###
    op.create_table('tag',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=64), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_table('tags')
    op.drop_constraint(None, 'comments', type_='foreignkey')
    op.create_foreign_key(None, 'comments', 'user', ['author_id'], ['id'])
    op.drop_column('comments', 'author')
    op.drop_constraint(None, 'post_tags', type_='foreignkey')
    op.create_foreign_key(None, 'post_tags', 'tag', ['tag_id'], ['id'])
    op.create_unique_constraint(None, 'role', ['name'])
    op.create_foreign_key(None, 'role_users', 'role', ['role_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
# ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'role_users', type_='foreignkey')
    op.drop_constraint(None, 'role', type_='unique')
    op.drop_constraint(None, 'post_tags', type_='foreignkey')
    op.create_foreign_key(None, 'post_tags', 'tags', ['tag_id'], ['id'])
    op.add_column('comments', sa.Column('author', sa.TEXT(), nullable=True))
    op.drop_constraint(None, 'comments', type_='foreignkey')
    op.create_foreign_key(None, 'comments', 'user', ['disabled'], ['id'])
    op.create_table('tags',
    sa.Column('id', sa.NullType(), nullable=False),
    sa.Column('title', sa.TEXT(length=64), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_table('tag')
    # ### end Alembic commands ###
